execute pathogen#infect()
map <leader>s :source ~/.vimrc<CR>

filetype on
syntax on
set nocompatible
set number
set hidden
set history=100
filetype indent on
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent
set hlsearch
set showmatch
set noshowmode
set laststatus=2

colorscheme monokai
set t_Co=256
